version: "3.9"

services:
  db:
    image: postgres:13.8
    container_name: chatroom_db
    env_file:
      - ./.env
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    restart: always

  app:
    build: .
    container_name: chatroom_back
    command: sh -c "
      python manage.py migrate &&
      python3 -m uvicorn config.asgi:django_application --host 0.0.0.0 --port 8000  --workers 4  --log-level debug --reload
      "
    volumes:
      - .:/app
      - ./static:/app/static
      - ./media:/app/media
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
    restart: always

  frontend:
    build: ./frontend
    container_name: chatroom_front
    volumes:
      - ./frontend:/app/frontend
    ports:
      - "5173:5173"
    depends_on:
      - app
    command: npm run dev


volumes:
  pgdata: