# Generated by Django 4.2.4 on 2023-09-01 13:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="server",
            old_name="member",
            new_name="members",
        ),
    ]
