# Generated by Django 4.2.4 on 2023-09-01 14:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0002_rename_member_server_members"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="description",
            new_name="topic",
        ),
    ]
