# Generated by Django 4.2.4 on 2023-09-03 05:41

import django.db.models.deletion
from django.db import migrations, models

import apps.server.utils


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0003_rename_description_room_topic"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="icon",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.server.utils.category_icon_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="server",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="room_server",
                to="server.server",
            ),
        ),
        migrations.AlterField(
            model_name="server",
            name="description",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
