# Generated by Django 4.2.4 on 2023-09-03 07:50

from django.db import migrations, models

import apps.server.utils


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0004_category_icon_alter_room_server_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="banner",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.server.utils.room_banner_upload_path,
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="icon",
            field=models.ImageField(
                blank=True, null=True, upload_to=apps.server.utils.room_icon_upload_path
            ),
        ),
    ]
