# Generated by Django 4.2.4 on 2023-09-07 06:51

import apps.server.utils
import apps.server.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0005_room_banner_room_icon"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
        migrations.RemoveField(
            model_name="room",
            name="banner",
        ),
        migrations.RemoveField(
            model_name="room",
            name="icon",
        ),
        migrations.AddField(
            model_name="server",
            name="banner",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.server.utils.room_banner_upload_path,
                validators=[apps.server.validators.validate_image_file_type],
            ),
        ),
        migrations.AddField(
            model_name="server",
            name="icon",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.server.utils.room_icon_upload_path,
                validators=[
                    apps.server.validators.validate_icon_size,
                    apps.server.validators.validate_image_file_type,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="icon",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.server.utils.category_icon_upload_path,
                validators=[apps.server.validators.validate_icon_size],
            ),
        ),
    ]
